if(typeof lucide!=='undefined'&&lucide.createIcons)lucide.createIcons();
function ri(){if(typeof lucide!=='undefined'&&lucide.createIcons)lucide.createIcons()}

// Close dropdowns on outside click
document.addEventListener('click',function(e){
    if(!e.target.closest('.content-dd')){document.querySelectorAll('.content-dd.open').forEach(function(d){d.classList.remove('open')})}
});

(function(){var c=document.getElementById('heroCanvas'),ctx=c.getContext('2d');if(!c||!ctx)return;var w,h,ps=[],ms={x:-999,y:-999};function rs(){w=c.width=c.offsetWidth;h=c.height=c.offsetHeight}rs();window.addEventListener('resize',rs);function P(){this.x=Math.random()*w;this.y=Math.random()*h;this.vx=(Math.random()-.5)*.4;this.vy=(Math.random()-.5)*.4;this.r=Math.random()*1.5+.5;this.o=Math.random()*.5+.1}for(var i=0;i<70;i++)ps.push(new P());document.addEventListener('mousemove',function(e){var r=c.getBoundingClientRect();ms.x=e.clientX-r.left;ms.y=e.clientY-r.top});function lp(){ctx.clearRect(0,0,w,h);for(var i=0;i<ps.length;i++){var p=ps[i];p.x+=p.vx;p.y+=p.vy;var dx=ms.x-p.x,dy=ms.y-p.y,d=Math.sqrt(dx*dx+dy*dy);if(d<150){p.x-=dx*.005;p.y-=dy*.005}if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle='rgba(0,166,81,'+p.o+')';ctx.fill();for(var j=i+1;j<ps.length;j++){var q=ps[j],dx2=p.x-q.x,dy2=p.y-q.y,d2=Math.sqrt(dx2*dx2+dy2*dy2);if(d2<120){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.strokeStyle='rgba(0,166,81,'+(0.08*(1-d2/120))+')';ctx.stroke()}}}requestAnimationFrame(lp)}lp()})();

var cg=document.getElementById('cursorGlow');if(cg)document.addEventListener('mousemove',function(e){cg.style.left=e.clientX+'px';cg.style.top=e.clientY+'px'});
function trackMouse(e,el){var r=el.getBoundingClientRect();el.style.setProperty('--mx',(e.clientX-r.left)+'px');el.style.setProperty('--my',(e.clientY-r.top)+'px')}

var nav=document.getElementById('nav');
window.addEventListener('scroll',function(){if(window.scrollY>60){nav.style.background='rgba(8,8,12,.85)';nav.style.backdropFilter='blur(24px)';nav.style.borderBottom='1px solid rgba(255,255,255,.05)'}else{nav.style.background='transparent';nav.style.backdropFilter='none';nav.style.borderBottom='none'}var b=document.getElementById('btt');if(window.scrollY>500){b.style.opacity='1';b.style.pointerEvents='auto'}else{b.style.opacity='0';b.style.pointerEvents='none'}});
var mobO=false;function toggleMob(){mobO=!mobO;document.getElementById('mobMenu').classList.toggle('hidden');document.getElementById('mobIcon').setAttribute('data-lucide',mobO?'x':'menu');ri()}function closeMob(){mobO=false;document.getElementById('mobMenu').classList.add('hidden');document.getElementById('mobIcon').setAttribute('data-lucide','menu');ri()}
document.querySelectorAll('a[href^="#"]').forEach(function(a){a.addEventListener('click',function(e){e.preventDefault();var t=document.querySelector(this.getAttribute('href'));if(t)t.scrollIntoView({behavior:'smooth',block:'start'})})});
function ac(){document.querySelectorAll('.counter').forEach(function(c){var t=+c.dataset.target;if(!t||c.dataset.done)return;if(c.getBoundingClientRect().top<innerHeight*.9){c.dataset.done='1';var cur=0,inc=t/50,tm=setInterval(function(){cur+=inc;if(cur>=t){c.textContent=t+(t===99?'%':t===65?'M+':'');clearInterval(tm)}else c.textContent=Math.floor(cur)+(t===99?'%':t===65?'M+':'')},30)}})}window.addEventListener('scroll',ac);window.addEventListener('load',ac);
function rv(){document.querySelectorAll('[data-r]').forEach(function(el){if(el.getBoundingClientRect().top<innerHeight*.88)el.classList.add('show')})}window.addEventListener('scroll',rv);window.addEventListener('load',rv);
var hp=document.getElementById('heroPhone');if(hp)document.addEventListener('mousemove',function(e){var r=hp.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=(e.clientX-cx)/innerWidth*15,dy=(e.clientY-cy)/innerHeight*10;hp.style.transform='rotateY('+(-8+dx)+'deg) rotateX('+(3-dy)+'deg)'});
function switchTab(t){document.querySelectorAll('.ptab').forEach(function(b){b.classList.remove('tab-on');b.classList.add('tab-off')});document.querySelector('[data-t="'+t+'"]').classList.remove('tab-off');document.querySelector('[data-t="'+t+'"]').classList.add('tab-on');document.querySelectorAll('.pcont').forEach(function(c){c.classList.add('hidden')});var el=document.getElementById('t-'+t);el.classList.remove('hidden');el.style.animation='fadeUp .5s ease forwards';ri()}

// Content Dropdown Toggle
function toggleDD(id){var dd=document.getElementById(id);var wasOpen=dd.classList.contains('open');document.querySelectorAll('.content-dd.open').forEach(function(d){if(d.id!==id)d.classList.remove('open')});if(wasOpen)dd.classList.remove('open');else dd.classList.add('open')}

// Filter services
function filterCat(cat,el){if(el){el.closest('.content-dd-menu').querySelectorAll('.content-dd-item').forEach(function(i){i.classList.remove('selected')});el.classList.add('selected')}document.querySelectorAll('.svc-card').forEach(function(c){if(cat==='all'||c.dataset.cat===cat){c.style.display='';c.style.animation='fadeUp .4s ease forwards'}else{c.style.display='none'}});document.getElementById('catFilter').classList.remove('open');ri()}

// Sort
function sortSv(type,el){if(el){el.closest('.content-dd-menu').querySelectorAll('.content-dd-item').forEach(function(i){i.classList.remove('selected')});el.classList.add('selected')}var grid=document.getElementById('servicesGrid');var cards=Array.from(grid.querySelectorAll('.svc-card'));cards.sort(function(a,b){if(type==='alpha')return a.querySelector('h3').textContent.localeCompare(b.querySelector('h3').textContent);return 0});cards.forEach(function(c){grid.appendChild(c)});document.getElementById('sortFilter').classList.remove('open')}

// Toast
function toast(msg,type){type=type||'success';var c=document.getElementById('toasts'),t=document.createElement('div');var cl={success:'rgba(0,166,81,.92)',error:'rgba(239,68,68,.92)',info:'rgba(0,114,188,.92)'};var ic={success:'check-circle',error:'alert-circle',info:'info'};t.className='toast-msg px-5 py-3 rounded-xl flex items-center gap-3 shadow-2xl min-w-[280px]';t.style.background=cl[type];t.style.backdropFilter='blur(10px)';t.innerHTML='<i data-lucide="'+ic[type]+'" class="w-5 h-5 flex-shrink-0"></i><span class="text-[13px] font-medium">'+msg+'</span>';c.appendChild(t);ri();setTimeout(function(){t.style.opacity='0';t.style.transform='translateX(100%)';t.style.transition='all .3s';setTimeout(function(){t.remove()},300)},3000)}

// Ripple
document.addEventListener('click',function(e){var btn=e.target.closest('.ripple-fx');if(!btn)return;var r=btn.getBoundingClientRect(),rp=document.createElement('span');rp.className='rp';var s=Math.max(r.width,r.height);rp.style.width=rp.style.height=s+'px';rp.style.left=(e.clientX-r.left-s/2)+'px';rp.style.top=(e.clientY-r.top-s/2)+'px';btn.appendChild(rp);setTimeout(function(){rp.remove()},600)});

// Modals
function openModal(id){var m=document.getElementById(id);m.classList.remove('hidden');m.classList.add('flex');m.style.opacity='0';m.querySelector('.modal-box').style.transform='scale(.95)';m.querySelector('.modal-box').style.opacity='0';requestAnimationFrame(function(){m.style.opacity='1';m.querySelector('.modal-box').style.transform='scale(1)';m.querySelector('.modal-box').style.opacity='1'});document.body.style.overflow='hidden';ri()}
function closeM(id){var m=document.getElementById(id);m.style.opacity='0';m.querySelector('.modal-box').style.transform='scale(.95)';m.querySelector('.modal-box').style.opacity='0';setTimeout(function(){m.classList.add('hidden');m.classList.remove('flex');document.body.style.overflow=''},300)}
document.addEventListener('keydown',function(e){if(e.key==='Escape')document.querySelectorAll('.modal-bg').forEach(function(m){if(!m.classList.contains('hidden'))closeM(m.id)})});

function doLogin(e){e.preventDefault();var b=document.getElementById('loginBtn');b.innerHTML='<span class="inline-block w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></span> Signing in...';b.disabled=true;setTimeout(function(){closeM('loginM');toast('Welcome back!');b.textContent='Sign In';b.disabled=false;e.target.reset()},1500)}
function selAmt(btn){document.querySelectorAll('.ambtn').forEach(function(b){b.style.borderColor='';b.style.background=''});btn.style.borderColor='rgba(0,166,81,.5)';btn.style.background='rgba(0,166,81,.15)'}
function clrAmt(){document.querySelectorAll('.ambtn').forEach(function(b){b.style.borderColor='';b.style.background=''})}
function doRecharge(e){e.preventDefault();var b=document.getElementById('rechargeBtn');b.innerHTML='<span class="inline-block w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></span> Processing...';b.disabled=true;setTimeout(function(){closeM('rechargeM');toast('Recharge successful!');b.innerHTML='Recharge Now';b.disabled=false;e.target.reset();clrAmt();ri()},2000)}
function submitContact(e){e.preventDefault();var b=document.getElementById('contactBtn');b.innerHTML='<span class="inline-block w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></span> Sending...';b.disabled=true;setTimeout(function(){toast('Message sent!');b.innerHTML='<i data-lucide="send" class="w-4 h-4"></i>Send Message';b.disabled=false;e.target.reset();ri()},1500)}
function pickPlan(n,p){toast(n+' ('+p+') selected!')}

// Service Detail
var SD={mobile:{icon:'smartphone',color:'text-emerald-400',bg:'from-emerald-500/20',title:'Mobile Services',desc:'Prepaid & postpaid mobile plans with voice, SMS, and data bundles.',f:['Prepaid & Postpaid Plans','Voice & Video Calls','SMS & MMS','Data Bundles','National & International Roaming','Number Portability']},internet:{icon:'wifi',color:'text-blue-400',bg:'from-blue-500/20',title:'Internet Services',desc:'High-speed 4G/5G mobile broadband and fiber-to-home internet.',f:['4G LTE Broadband','5G NR (Selected Cities)','Fiber-to-the-Home','Wireless Broadband','Dedicated Internet','CDN & Cloud']},telebirr:{icon:'wallet',color:'text-green-400',bg:'from-green-500/20',title:'Telebirr',desc:'Ethiopia\'s #1 mobile money platform for payments and finance.',f:['Person-to-Person Transfers','Bill Payments','Merchant Payments','Bank Linking','International Remittance','Savings & Loans']},enterprise:{icon:'building',color:'text-purple-400',bg:'from-purple-500/20',title:'Enterprise Solutions',desc:'Tailored telecom solutions for businesses.',f:['MPLS & SD-WAN','Cloud & Hosting','Managed Networks','Unified Communications','IoT Solutions','Account Management']},intl:{icon:'plane',color:'text-orange-400',bg:'from-orange-500/20',title:'International Calling',desc:'Affordable international calling and data roaming.',f:['International Voice','Data Roaming','SIM-Based Roaming','Country Bundles','Calling Cards','VoIP Solutions']},vas:{icon:'gift',color:'text-cyan-400',bg:'from-cyan-500/20',title:'Value Added Services',desc:'Enhance your mobile experience with extra features.',f:['Caller Tunes','Missed Call Alert','SMS Bundles','News Alerts','Games & Entertainment','Location Services']}};
function openService(k){var d=SD[k];document.getElementById('serviceMC').innerHTML='<div class="flex items-center gap-4 mb-6"><div class="w-14 h-14 rounded-2xl bg-gradient-to-br '+d.bg+' to-transparent flex items-center justify-center"><i data-lucide="'+d.icon+'" class="w-7 h-7 '+d.color+'"></i></div><div><h3 class="text-xl font-semibold">'+d.title+'</h3><p class="text-[11px] text-gray-600">ethio telecom</p></div></div><p class="text-gray-400 font-light text-[13px] leading-relaxed mb-6">'+d.desc+'</p><h4 class="text-[13px] font-semibold mb-4">Key Features</h4><ul class="space-y-2.5 mb-6">'+d.f.map(function(f){return '<li class="flex items-center gap-3 text-[13px] text-gray-300"><i data-lucide="check-circle" class="w-4 h-4 '+d.color+' flex-shrink-0"></i>'+f+'</li>'}).join('')+'</ul><button onclick="closeM(\'serviceM\');toast(\'Redirecting...\',\'info\')" class="btn-glow w-full py-3 rounded-full text-[13px] font-semibold ripple-fx">Explore '+d.title+'</button>';openModal('serviceM')}
